
$(document).ready(function(){
  $(".plus").click(function(){
  	$(this).toggleClass("down");
    $(".1").slideToggle("slow");
  });
});
$(document).ready(function(){
  $(".plus"+2).click(function(){
  	$(this).toggleClass("down");
    $(".2").slideToggle("slow");
  });
});
$(document).ready(function(){
  $(".plus"+3).click(function(){
  	$(this).toggleClass("down");
    $(".3").slideToggle("slow");
  });
});
$(document).ready(function(){
  $(".plus"+4).click(function(){
  	$(this).toggleClass("down");
    $(".4").slideToggle("slow");
  });
});
$(document).ready(function(){
  $(".plus"+5).click(function(){
  	$(this).toggleClass("down");
    $(".5").slideToggle("slow");
  });
});
$(document).ready(function(){
  $(".plus"+6).click(function(){
  	$(this).toggleClass("down");
    $(".6").slideToggle("slow");
  });
});
$(document).ready(function(){
  $(".plus"+7).click(function(){
  	$(this).toggleClass("down");
    $(".7").slideToggle("slow");
  });
});